# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-01 14:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20170801_1428'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('match', models.CharField(default='#', max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_module_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_module_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '1. Modules',
                'ordering': ['order'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('match', models.CharField(default='#', max_length=200)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_moduleitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_moduleitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
            ],
            options={
                'verbose_name_plural': '2. Module Items',
                'ordering': ['module'],
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemodule_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemodule_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Module')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Role')),
            ],
            options={
                'verbose_name_plural': '3. Module Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('moduleitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleItem')),
                ('permission', models.ManyToManyField(blank=True, to='core.Permission')),
                ('role_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.RoleModule')),
            ],
            options={
                'verbose_name_plural': '4. Module Item Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rolemoduleitem',
            unique_together=set([('role_module', 'moduleitem')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolemodule',
            unique_together=set([('module',)]),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together=set([('name',)]),
        ),
    ]
