# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order'], 'verbose_name_plural': '1. Modules'},
        ),
        migrations.AlterModelOptions(
            name='moduleitem',
            options={'ordering': ['module'], 'verbose_name_plural': '2. Module Items'},
        ),
        migrations.AlterModelOptions(
            name='moduleitemteam',
            options={'verbose_name_plural': '4. Module Item Teams'},
        ),
        migrations.AlterModelOptions(
            name='moduleteam',
            options={'verbose_name_plural': '3. Module Teams'},
        ),
    ]
