# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170104_1104'),
        ('module', '0003_auto_20170106_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleteam',
            name='team',
        ),
        migrations.AddField(
            model_name='moduleteam',
            name='team',
            field=models.ManyToManyField(to='core.Team'),
        ),
    ]
