# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170227_0144'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0004_auto_20170106_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_modulerole_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_modulerole_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.Module')),
                ('role', models.ManyToManyField(to='core.Role')),
            ],
            options={
                'verbose_name_plural': '3. Module Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduleteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='team',
        ),
        migrations.AlterField(
            model_name='moduleitemteam',
            name='module_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleRole'),
        ),
        migrations.DeleteModel(
            name='ModuleTeam',
        ),
        migrations.AlterUniqueTogether(
            name='modulerole',
            unique_together=set([('module',)]),
        ),
    ]
