# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('module', '0005_auto_20170227_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleItemRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_moduleitemrole_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_moduleitemrole_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleRole')),
                ('moduleitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleItem')),
            ],
            options={
                'verbose_name_plural': '4. Module Item Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduleitemteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='module_team',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='moduleitem',
        ),
        migrations.DeleteModel(
            name='ModuleItemTeam',
        ),
        migrations.AlterUniqueTogether(
            name='moduleitemrole',
            unique_together=set([('module_team', 'moduleitem')]),
        ),
    ]
