# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_permission'),
        ('module', '0005_auto_20170227_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='permission',
        ),
        migrations.AddField(
            model_name='moduleitemteam',
            name='permission',
            field=models.ManyToManyField(blank=True, to='core.Permission'),
        ),
    ]
