# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import project_name.apps.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20170227_0341'),
        ('module', '0006_auto_20170227_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemodule_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemodule_modified_by', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.Module')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Role')),
            ],
            options={
                'verbose_name_plural': '3. Module Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RoleModuleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('created_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_rolemoduleitem_modified_by', to=settings.AUTH_USER_MODEL)),
                ('moduleitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.ModuleItem')),
                ('permission', models.ManyToManyField(blank=True, to='core.Permission')),
                ('role_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.RoleModule')),
            ],
            options={
                'verbose_name_plural': '4. Module Item Teams',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='moduleitemteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='module_team',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='moduleitem',
        ),
        migrations.RemoveField(
            model_name='moduleitemteam',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='moduleteam',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleteam',
            name='team',
        ),
        migrations.DeleteModel(
            name='ModuleItemTeam',
        ),
        migrations.DeleteModel(
            name='ModuleTeam',
        ),
        migrations.AlterUniqueTogether(
            name='rolemoduleitem',
            unique_together=set([('role_module', 'moduleitem')]),
        ),
        migrations.AlterUniqueTogether(
            name='rolemodule',
            unique_together=set([('module',)]),
        ),
    ]
