# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0007_auto_20170227_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodule',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Role'),
        ),
    ]
