# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import project_name.apps.core.utils.upload_folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('is_ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to=project_name.apps.core.utils.upload_folder.upload_restaurant_menu, verbose_name='file')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='amount')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_restaurantmenu_restaurant', to='restaurant.Restaurant', verbose_name='restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('count_table', models.IntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_restauranttable_restaurant', to='restaurant.Restaurant', verbose_name='restaurant')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='restauranttable',
            unique_together=set([('position', 'restaurant')]),
        ),
        migrations.AlterUniqueTogether(
            name='restaurantmenu',
            unique_together=set([('restaurant', 'name')]),
        ),
    ]
