# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:42
from __future__ import unicode_literals

from django.db import migrations, models

import project_name.apps.core.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('objects', project_name.apps.core.manager.RoleManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('objects', project_name.apps.core.manager.TeamManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='code_name',
        ),
        migrations.AddField(
            model_name='role',
            name='codename',
            field=models.CharField(default='', max_length=80, unique=True, verbose_name='codename'),
            preserve_default=False,
        ),
    ]
