# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 02:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import project_name.apps.core.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170227_0228'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='permission',
            managers=[
                ('objects', project_name.apps.core.manager.PermissionManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='role',
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
    ]
