# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170227_0235'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permission',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('team', 'name', 'codename')]),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('name',)]),
        ),
    ]
