# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:04
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models

import project_name.apps.core.manager
import project_name.apps.core.utils.fields
import project_name.apps.core.utils.upload_folder


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('display_name', models.CharField(blank=True, max_length=14, null=True, verbose_name='display name')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_user',
                'abstract': False,
                'swappable': 'user.User',
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            managers=[
                ('objects', project_name.apps.core.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date created')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True, verbose_name='date modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_userprofile_user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('document_type', models.CharField(blank=True, choices=[('', '--Choose--'), ('DOC-1', 'DNI'), ('DOC-2', 'RUC'), ('DOC-3', 'PASSPORT')], max_length=10, null=True)),
                ('gender_type', models.CharField(blank=True, choices=[('', '--Choose--'), ('GEN-1', 'Male'), ('GEN-2', 'Female')], max_length=10, null=True)),
                ('document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('home_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('logo_profile', models.ImageField(blank=True, null=True, upload_to=project_name.apps.core.utils.upload_folder.upload_user_profile)),
            ],
            options={
                'db_table': 'user_profile',
                'verbose_name_plural': 'Profiles',
                'verbose_name': 'Profile',
            },
            managers=[
                ('current', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='core.Team', verbose_name='teams'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='core.Role', verbose_name='user roles'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by',
            field=project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userprofile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='modified_by',
            field=project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userprofile_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
