# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 13:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations

import project_name.apps.core.utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='created_by',
            field=project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userprofile_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='modified_by',
            field=project_name.apps.core.utils.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_userprofile_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
