# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='core.Team', verbose_name='teams'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_roles',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='core.Role', verbose_name='user roles'),
        ),
    ]
