# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cocinero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitcken_kitchenmenu_cocinero', to=settings.AUTH_USER_MODEL, verbose_name='cocinero')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitcken_kitchenmenu_reservation', to='reservation.Reservation', verbose_name='reservation')),
                ('reservationMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitcken_kitchenmenu_reservationMenu', to='reservation.ReservationMenu', verbose_name='reservation menu')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kitchenmenu',
            unique_together=set([('reservation', 'reservationMenu')]),
        ),
    ]
