# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest2', models.CharField(max_length=100)),
                ('person_total', models.IntegerField(default=1)),
                ('dateReservation', models.DateTimeField(blank=True, null=True, verbose_name='date reservation')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
                ('guest1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservation_guest1', to=settings.AUTH_USER_MODEL, verbose_name='mozo')),
                ('mozo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservation_mozo', to=settings.AUTH_USER_MODEL, verbose_name='mozo')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservation_restaurant', to='restaurant.Restaurant', verbose_name='restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kitchen_completed', models.BooleanField(default=False)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservationmenu_reservation', to='reservation.Reservation', verbose_name='reservation')),
                ('restaurantMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservationmenu_restaurantMenu', to='restaurant.RestaurantMenu', verbose_name='restaurant menu')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservationtable_reservation', to='reservation.Reservation', verbose_name='reservation')),
                ('restaurantTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_reservationtable_restaurantTable', to='restaurant.RestaurantTable', verbose_name='restaurant table')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='reservationtable',
            unique_together=set([('reservation', 'restaurantTable')]),
        ),
        migrations.AlterUniqueTogether(
            name='reservationmenu',
            unique_together=set([('reservation', 'restaurantMenu')]),
        ),
    ]
