# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20171024_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='guest2'),
        ),
    ]
